// 9 axes -- seven primes + substrate + theta
// Extracted verbatim from 9-axis-human-sonar/index.html.

export const AXES = [
  { p:2,  key:'substrate', sym:'◊', name:'Substrate', angle:0, hue:'#7a9c7e',
    question:"What is this at its core?",
    kw:['is essentially','at root','fundamentally','the core is','underneath everything','really is','actually','truly'],
    hedge:['sort of','kind of','maybe','i guess','not sure','whatever','something like','a thing'],
    landed:['it is','this is','the root','the source','core of it'] },
  { p:3,  key:'bloom', sym:'β', name:'Bloom', angle:1, hue:'#7a9c7e',
    question:"Where are you right now with it?",
    kw:['right now','currently','today','this week','at the moment','present','feeling','sitting with','holding'],
    hedge:['i suppose','i think','maybe','probably','fine','okay','alright'],
    landed:['i feel','i am','right now i','i notice','present with','sitting with'] },
  { p:5,  key:'function', sym:'ƒ', name:'Function', angle:2, hue:'#7a9c7e',
    question:"What are you doing about it?",
    kw:['doing','working on','trying','plan','action','next step','start','began','started','built','made','wrote','moved'],
    hedge:['want to','should','need to','going to','one day','someday','eventually','if i','maybe i'],
    landed:['i did','i started','i built','i made','i moved','i wrote','i shipped','i finished'] },
  { p:7,  key:'kappa', sym:'κ', name:'Kappa', angle:3, hue:'#7a9c7e',
    question:"Is that working?",
    kw:['working','landing','effective','helps','helping','failing','not working','stuck','moving','shifting','changing'],
    hedge:['i think it','seems to','maybe','not sure if','hard to tell','some days'],
    landed:['it is working','not working','stopped','landed','moved','shifted','changed something'] },
  { p:11, key:'omega', sym:'Ω', name:'Omega', angle:4, hue:'#7a9c7e',
    question:"What's the next call?",
    kw:['decide','decision','call','choose','choice','next','will','going to','tomorrow','committed','agreed'],
    hedge:['might','could','maybe','depends','see how','play it by ear','if things','wait and'],
    landed:['i will','decided','my call is','i choose','committed to','the next thing i'] },
  { p:13, key:'psi', sym:'ψ', name:'Psi', angle:5, hue:'#7a9c7e',
    question:"How do you feel about it?",
    kw:['feel','feeling','felt','sense','body','gut','notice','aware','tender','angry','sad','afraid','joy','grief','tight','loose','warm','cold','heart','chest','stomach'],
    hedge:['fine','okay','alright','not much','nothing','whatever',"doesn't matter","can't tell",'numb'],
    landed:['i feel','in my body','a knot','tightness','warmth','tears','grief','joy','trembling'] },
  { p:17, key:'numero', sym:'№', name:'Numero', angle:6, hue:'#7a9c7e',
    question:"How much has this cost you?",
    kw:['cost','years','months','weeks','times','many','so much','lost','gave up','sacrificed','spent','burned','wasted'],
    hedge:['some','a bit','a while','not much',"don't know","can't say",'a few'],
    landed:['it cost me','years of','i lost','i gave up','sacrificed','spent','burned through'] },
  { p:19, key:'rupee', sym:'₹', name:'Rupee', angle:7, hue:'#d4a052',
    question:"What's it worth to fix?",
    kw:['worth','value','pay','price','invest','commit','deserve','earned','give','offer','trade'],
    hedge:['worth something','some value','a bit','not sure','depends','maybe','some money'],
    landed:["it's worth","i'd pay",'worth everything','deserve','earned','no price','my life'] },
  { p:23, key:'theta', sym:'θ', name:'Theta', angle:8, hue:'#d4a052',
    question:"From where you sit, what's the shape?",
    kw:['shape','pattern','rhythm','cycle','again','always','never','pattern','structure of it','from where','looking at','see it as','frame','angle'],
    hedge:['just how it is','always was',"can't see it any other",'one way'],
    landed:['the pattern is','the shape is','the rhythm','the cycle','from here it looks','shifted my angle','see it differently now'] },
];

export const AXIS_BY_KEY = Object.fromEntries(AXES.map(a => [a.key, a]));

export const PROBES = {
  substrate:[
    "What is this at its core?",
    "If you strip away everything else, what's left?",
    "What's this really about?",
    "Underneath the story, what's the source?",
  ],
  bloom:[
    "Where are you with it right this second?",
    "What's true for you right now?",
    "How is it landing today, not in general?",
    "Say it in present tense -- what's alive now?",
  ],
  function:[
    "What are you actually doing about it?",
    "What's the next concrete move?",
    "What have you tried this week?",
    "What would action look like tomorrow morning?",
  ],
  kappa:[
    "Is what you're doing actually working?",
    "How would you know if it wasn't?",
    "What's the honest read on your own approach?",
    "If a friend was doing what you're doing, what would you notice?",
  ],
  omega:[
    "What's the next call -- the actual decision?",
    "If you had to choose today, what would you choose?",
    "What are you deciding by not deciding?",
    "What decision would make everything else easier?",
  ],
  psi:[
    "How does it feel in your body right now?",
    "Where do you notice it -- chest, gut, throat?",
    "What's the feeling underneath the thought?",
    "If the feeling had a shape or colour, what would it be?",
  ],
  numero:[
    "How much has this cost you already?",
    "How many years have you been carrying this?",
    "What have you had to give up to keep this alive?",
    "Count the price -- literally.",
  ],
  rupee:[
    "What's it worth to you to actually resolve this?",
    "What would you pay to have it handled?",
    "How valuable is your own peace here?",
    "If you priced your own worth in this, what would it be?",
  ],
  theta:[
    "From where you sit now, what shape does the whole thing have?",
    "What's the rhythm -- how does the pattern cycle?",
    "If you shifted position, what would look different?",
    "What angle haven't you looked at this from?",
  ],
};
